name = "sentry-ingest-relay"
main = "./src/index.ts"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat", "no_minimal_subrequests"]

[placement]
mode = "smart"

[limits]
cpu_ms = 50
